/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package telaJogo;

import views.TelaInicio;
import java.awt.Color;

/**
 *
 * @author rb29
 */
public class Tela1 extends javax.swing.JFrame {

    /**
     * Creates new form Tela11
     */
    public Tela1() {
        initComponents();
        setExtendedState(MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        txtR = new javax.swing.JFormattedTextField();
        txtE = new javax.swing.JFormattedTextField();
        txtL = new javax.swing.JFormattedTextField();
        txtO = new javax.swing.JFormattedTextField();
        txtG = new javax.swing.JFormattedTextField();
        txtI = new javax.swing.JFormattedTextField();
        txtOO = new javax.swing.JFormattedTextField();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(102, 0, 153));

        jPanel1.setBackground(new java.awt.Color(102, 0, 153));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/xclock_clock_time_5987.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 70, 270, 230));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("Digite o nome do objeto referente a imagem:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 50, 390, 30));

        jButton5.setBackground(new java.awt.Color(255, 255, 255));
        jButton5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton5.setText("Início");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 400, 130, 40));

        jButton8.setBackground(new java.awt.Color(255, 255, 255));
        jButton8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton8.setText("Anterior");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 400, 130, 40));

        try {
            txtR.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("U")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtRActionPerformed(evt);
            }
        });
        txtR.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtRKeyReleased(evt);
            }
        });
        jPanel1.add(txtR, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 310, 40, 40));

        try {
            txtE.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("U")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtE.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtEKeyReleased(evt);
            }
        });
        jPanel1.add(txtE, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 310, 40, 40));

        try {
            txtL.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("U")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtLActionPerformed(evt);
            }
        });
        txtL.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtLKeyReleased(evt);
            }
        });
        jPanel1.add(txtL, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 310, 40, 40));

        try {
            txtO.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("U")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtOActionPerformed(evt);
            }
        });
        txtO.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtOKeyReleased(evt);
            }
        });
        jPanel1.add(txtO, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 310, 40, 40));

        txtG.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtGKeyReleased(evt);
            }
        });
        jPanel1.add(txtG, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 310, 40, 40));

        txtI.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtIKeyReleased(evt);
            }
        });
        jPanel1.add(txtI, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 310, 40, 40));

        txtOO.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtOOKeyReleased(evt);
            }
        });
        jPanel1.add(txtOO, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 310, 40, 40));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Logo.png"))); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel3)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(219, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 599, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(183, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 201, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        setSize(new java.awt.Dimension(1017, 741));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        this.dispose();
        TelaInicio tela = new TelaInicio();
        tela.setVisible(true);
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
        Tela1 tela=new Tela1();
        tela.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton8ActionPerformed

    private void txtRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtRActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtRActionPerformed

    private void txtRKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtRKeyReleased
        // TODO add your handling code here:
        if(txtR.getText().equals("R")){
            txtR.setBackground(Color.green);
            txtE.setVisible(true);
            txtE.requestFocus();
        }else{
            txtR.setBackground(Color.RED);
            txtR.selectAll();
        }
    }//GEN-LAST:event_txtRKeyReleased

    private void txtEKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtEKeyReleased
        // TODO add your handling code here:
        if(txtE.getText().equals("E")){
            txtE.setBackground(Color.green);
            txtL.setVisible(true);
            txtL.requestFocus();

        }else{
            txtE.setBackground(Color.RED);
            txtE.selectAll();
        }
    }//GEN-LAST:event_txtEKeyReleased

    private void txtLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtLActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtLActionPerformed

    private void txtLKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtLKeyReleased
        // TODO add your handling code here:
        if(txtL.getText().equals("L")){
            txtL.setBackground(Color.green);
            txtO.setVisible(true);
            txtO.requestFocus();

        }else{
            txtL.setBackground(Color.RED);
            txtL.selectAll();
        }
    }//GEN-LAST:event_txtLKeyReleased

    private void txtOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtOActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtOActionPerformed

    private void txtOKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtOKeyReleased
        // TODO add your handling code here:
        if(txtO.getText().equals("O")){
            txtO.setBackground(Color.green);
            txtG.setVisible(true);
            txtG.requestFocus();

        }else{
            txtO.setBackground(Color.RED);
            txtO.selectAll();
        }
    }//GEN-LAST:event_txtOKeyReleased

    private void txtGKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtGKeyReleased
        // TODO add your handling code here:
          if(txtG.getText().equals("G")){
            txtG.setBackground(Color.green);
            txtI.setVisible(true);
            txtI.requestFocus();

        }else{
            txtG.setBackground(Color.RED);
            txtG.selectAll();
        }
    }//GEN-LAST:event_txtGKeyReleased

    private void txtIKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtIKeyReleased
        // TODO add your handling code here:
         if(txtI.getText().equals("I")){
            txtI.setBackground(Color.green);
            txtOO.setVisible(true);
            txtOO.requestFocus();

        }else{
            txtI.setBackground(Color.RED);
            txtI.selectAll();
        }
    }//GEN-LAST:event_txtIKeyReleased

    private void txtOOKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtOOKeyReleased
        // TODO add your handling code here:
        if(txtOO.getText().equals("O")){
            txtOO.setBackground(Color.green);
            new Tela2().setVisible(true);
            this.dispose();

        }else{
            txtOO.setBackground(Color.RED);
            txtOO.selectAll();
        }
    }//GEN-LAST:event_txtOOKeyReleased

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        
        txtE.setVisible(false);
        txtL.setVisible(false);
        txtO.setVisible(false);
        txtG.setVisible(false);
        txtI.setVisible(false);
        txtOO.setVisible(false);
    }//GEN-LAST:event_formWindowOpened

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tela1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tela1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tela1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tela1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Tela1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton8;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JFormattedTextField txtE;
    private javax.swing.JFormattedTextField txtG;
    private javax.swing.JFormattedTextField txtI;
    private javax.swing.JFormattedTextField txtL;
    private javax.swing.JFormattedTextField txtO;
    private javax.swing.JFormattedTextField txtOO;
    private javax.swing.JFormattedTextField txtR;
    // End of variables declaration//GEN-END:variables
}
