/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

import controle.AtividadeControler;
import java.awt.Color;
import java.awt.Font;
import java.util.ArrayList;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import model.Atividade;
import javax.swing.ImageIcon;
import javax.swing.UIManager;

/**
 *
 * @author rb29
 */
public class TelaProfessor extends javax.swing.JFrame {

    DefaultComboBoxModel modelo;

    Atividade atividade;

    /**
     * Creates new form TelaTrop
     */
    public TelaProfessor() {
        initComponents();

        setExtendedState(MAXIMIZED_BOTH);

       

        modelo = (DefaultComboBoxModel) option.getModel();
        buscarAtividade();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        opcao2 = new javax.swing.JButton();
        opcao3 = new javax.swing.JButton();
        opcao4 = new javax.swing.JButton();
        opcao1 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        option = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jLabelDescricao = new javax.swing.JLabel();
        jLabelPergunta = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(null);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel2.setText("B");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(250, 450, 30, 40);

        jLabel3.setBackground(new java.awt.Color(0, 0, 0));
        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel3.setText("A");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(250, 380, 30, 40);

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setText("Descrição");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(650, 120, 80, 20);

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel6.setText("Pergunta");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(650, 190, 90, 40);

        opcao2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        opcao2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opcao2ActionPerformed(evt);
            }
        });
        jPanel1.add(opcao2);
        opcao2.setBounds(290, 450, 360, 40);

        opcao3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        opcao3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opcao3ActionPerformed(evt);
            }
        });
        jPanel1.add(opcao3);
        opcao3.setBounds(740, 380, 360, 40);

        opcao4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        opcao4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opcao4ActionPerformed(evt);
            }
        });
        jPanel1.add(opcao4);
        opcao4.setBounds(740, 450, 360, 40);

        opcao1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        opcao1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opcao1ActionPerformed(evt);
            }
        });
        jPanel1.add(opcao1);
        opcao1.setBounds(290, 380, 360, 40);

        jLabel8.setBackground(new java.awt.Color(255, 255, 255));
        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel8.setText("C");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(710, 380, 30, 40);

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel9.setText("D");
        jLabel9.setAutoscrolls(true);
        jPanel1.add(jLabel9);
        jLabel9.setBounds(710, 450, 30, 40);

        option.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                optionItemStateChanged(evt);
            }
        });
        option.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                optionMouseReleased(evt);
            }
        });
        option.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                optionActionPerformed(evt);
            }
        });
        jPanel1.add(option);
        option.setBounds(560, 30, 240, 30);

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton1.setText("Início");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(620, 563, 180, 30);

        jLabelDescricao.setBackground(new java.awt.Color(255, 255, 255));
        jLabelDescricao.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jPanel1.add(jLabelDescricao);
        jLabelDescricao.setBounds(470, 160, 710, 30);

        jLabelPergunta.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jPanel1.add(jLabelPergunta);
        jLabelPergunta.setBounds(480, 240, 750, 40);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Logo.png"))); // NOI18N
        jPanel1.add(jLabel4);
        jLabel4.setBounds(0, 0, 200, 57);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 1546, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 708, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void optionItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_optionItemStateChanged

        atividade = (Atividade) modelo.getSelectedItem();

      
        jLabelDescricao.setText(atividade.getDescricao());
        jLabelPergunta.setText(atividade.getPergunta());
        opcao1.setText(atividade.getOpcao1());
        opcao2.setText(atividade.getOpcao2());
        opcao3.setText(atividade.getOpcao3());
        opcao4.setText(atividade.getOpcao4());
       
    }
    public void buscarAtividade() {
        AtividadeControler controle = new AtividadeControler();
        ArrayList<Atividade> vetorDeAtividades = controle.buscarAtividade();
        for (Atividade u : vetorDeAtividades) {
            modelo.addElement(u);
        }
    }//GEN-LAST:event_optionItemStateChanged

    private void optionMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_optionMouseReleased

    }//GEN-LAST:event_optionMouseReleased

    private void optionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_optionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_optionActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
         this.dispose();
        TelaInicio tela = new TelaInicio();
        tela.setVisible(true);    
    }//GEN-LAST:event_jButton1ActionPerformed

    private void opcao1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opcao1ActionPerformed
        verificaResposta(evt);
    }//GEN-LAST:event_opcao1ActionPerformed

    private void opcao3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opcao3ActionPerformed
        // TODO add your handling code here:
        verificaResposta(evt);
    }//GEN-LAST:event_opcao3ActionPerformed

    private void opcao4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opcao4ActionPerformed
        // TODO add your handling code here:
        verificaResposta(evt);
    }//GEN-LAST:event_opcao4ActionPerformed

    private void opcao2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opcao2ActionPerformed
        // TODO add your handling code here:
        verificaResposta(evt);
    }//GEN-LAST:event_opcao2ActionPerformed

    public void verificaResposta(java.awt.event.ActionEvent evt) {
        String opcaoCorreta = atividade.getResposta();
        ImageIcon icon = new ImageIcon(this.getClass().getResource("/imagens/acerto.png"));
        if (opcaoCorreta.equalsIgnoreCase(evt.getActionCommand())) {
            UIManager.put("OptionPane.messageFont", new Font("Arial", Font.BOLD, 24));
            UIManager.put("Panel.background", new Color(0,151,204));
            UIManager.getDefaults().put("OptionPane.background", new Color(0,151,204));
            JOptionPane.showMessageDialog(null, "Parabens", "Esconha outra atividade a cima", JOptionPane.INFORMATION_MESSAGE, icon);

        } else {
            UIManager.put("OptionPane.messageFont", new Font("Arial", Font.BOLD, 24));
            UIManager.put("Panel.background", new Color(0,151,204));
            UIManager.getDefaults().put("OptionPane.background", new Color(0,151,204));
            ImageIcon icons = new ImageIcon(this.getClass().getResource("/imagens/erro.png"));
            JOptionPane.showMessageDialog(null, "Você Errou", "Tente outra Opção", JOptionPane.INFORMATION_MESSAGE, icons);
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaProfessor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaProfessor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaProfessor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaProfessor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaProfessor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelDescricao;
    private javax.swing.JLabel jLabelPergunta;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton opcao1;
    private javax.swing.JButton opcao2;
    private javax.swing.JButton opcao3;
    private javax.swing.JButton opcao4;
    private javax.swing.JComboBox<String> option;
    // End of variables declaration//GEN-END:variables
}
