package views;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */


import java.awt.Graphics;
import java.awt.Image;
import javax.imageio.ImageIO;

/**
 *
 * @author rb29
 */
public class TelaDeFundo extends javax.swing.JInternalFrame {

    /**
     * Creates new form TelaDeFundo
     */
    public TelaDeFundo() {
        super(null,false,false,false);
        initComponents();
        try {
            fundo=javax.imageio.ImageIO.read(new java.net.URL(getClass().getResource("fundor.png"),"fundor.png"));
        } catch (Exception e){} 
        
    }
        public void paint(Graphics Fundo){
            Fundo.drawImage(fundo,0,0,getWidth(),getHeight(),this);
         }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pack();
    }// </editor-fold>//GEN-END:initComponents
protected static Image fundo;

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}

