/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package viewsCRUD;


import videos.SeletorArquivo;
import controle.AtividadeControler;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author rb29
 */
public class CadastroAtividade extends javax.swing.JInternalFrame {

    /**
     * Creates new form NewJInternalFrame
     */
    public CadastroAtividade() {
        initComponents();
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));
     
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jTextFieldId = new javax.swing.JTextField();
        jTextFieldTitulo = new javax.swing.JTextField();
        jTextFieldDescricao = new javax.swing.JTextField();
        jTextFieldPergunta = new javax.swing.JTextField();
        jTextFieldlOpcao1 = new javax.swing.JTextField();
        jTextFieldOpcao2 = new javax.swing.JTextField();
        jTextFieldOpcao3 = new javax.swing.JTextField();
        jTextFieldOpcao4 = new javax.swing.JTextField();
        jTextFieldResposta = new javax.swing.JTextField();
        imagem = new javax.swing.JLabel();
        bEditar = new javax.swing.JButton();
        bCadastrar = new javax.swing.JButton();
        bCancelar = new javax.swing.JButton();

        setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Cadastra Atividade", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 18))); // NOI18N
        setClosable(true);
        setMaximizable(true);
        setResizable(true);
        setVisible(false);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jPanel1.setBackground(new java.awt.Color(153, 204, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("ID");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(50, 10, 30, 30);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Titulo");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(40, 50, 40, 30);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Pergunta");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(10, 130, 70, 33);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Opcão A");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(420, 20, 60, 20);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("Opção C");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(420, 90, 60, 30);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("Descrição ");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(10, 90, 80, 32);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setText("Opção B");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(420, 50, 60, 30);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setText("Opção D");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(420, 130, 60, 30);

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setText("Resposta");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(420, 170, 64, 30);

        jTextFieldId.setEnabled(false);
        jTextFieldId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldIdActionPerformed(evt);
            }
        });
        jPanel1.add(jTextFieldId);
        jTextFieldId.setBounds(90, 10, 46, 30);
        jPanel1.add(jTextFieldTitulo);
        jTextFieldTitulo.setBounds(90, 50, 300, 30);

        jTextFieldDescricao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldDescricaoActionPerformed(evt);
            }
        });
        jPanel1.add(jTextFieldDescricao);
        jTextFieldDescricao.setBounds(90, 90, 300, 32);
        jPanel1.add(jTextFieldPergunta);
        jTextFieldPergunta.setBounds(90, 130, 300, 33);
        jPanel1.add(jTextFieldlOpcao1);
        jTextFieldlOpcao1.setBounds(490, 10, 160, 30);
        jPanel1.add(jTextFieldOpcao2);
        jTextFieldOpcao2.setBounds(490, 50, 160, 30);
        jPanel1.add(jTextFieldOpcao3);
        jTextFieldOpcao3.setBounds(490, 90, 160, 30);
        jPanel1.add(jTextFieldOpcao4);
        jTextFieldOpcao4.setBounds(490, 130, 160, 30);
        jPanel1.add(jTextFieldResposta);
        jTextFieldResposta.setBounds(490, 170, 160, 30);
        jPanel1.add(imagem);
        imagem.setBounds(350, 210, 290, 30);

        bEditar.setBackground(new java.awt.Color(255, 255, 255));
        bEditar.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        bEditar.setText("Editar");
        jPanel1.add(bEditar);
        bEditar.setBounds(250, 271, 160, 40);

        bCadastrar.setBackground(new java.awt.Color(255, 255, 255));
        bCadastrar.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        bCadastrar.setText("Cadastrar");
        bCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bCadastrarActionPerformed(evt);
            }
        });
        jPanel1.add(bCadastrar);
        bCadastrar.setBounds(30, 271, 140, 40);

        bCancelar.setBackground(new java.awt.Color(255, 255, 255));
        bCancelar.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        bCancelar.setText("Cancelar");
        bCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bCancelarActionPerformed(evt);
            }
        });
        jPanel1.add(bCancelar);
        bCancelar.setBounds(490, 271, 150, 40);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(42, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 670, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(60, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 347, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(66, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setBounds(0, 0, 744, 507);
    }// </editor-fold>//GEN-END:initComponents

    private void bCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bCadastrarActionPerformed
        // TODO add your handling code here:
        AtividadeControler controle = new AtividadeControler();
        controle.CadastrarAtividade(jTextFieldTitulo.getText(), jTextFieldDescricao.getText(), jTextFieldPergunta.getText(), jTextFieldlOpcao1.getText(), jTextFieldOpcao2.getText(), jTextFieldOpcao3.getText(), jTextFieldOpcao4.getText(), jTextFieldResposta.getText());
       
        dispose();

    }//GEN-LAST:event_bCadastrarActionPerformed

    private void jTextFieldDescricaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldDescricaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldDescricaoActionPerformed

    private void bCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bCancelarActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_bCancelarActionPerformed

    private void jTextFieldIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldIdActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bCadastrar;
    private javax.swing.JButton bCancelar;
    private javax.swing.JButton bEditar;
    private javax.swing.JLabel imagem;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField jTextFieldDescricao;
    private javax.swing.JTextField jTextFieldId;
    private javax.swing.JTextField jTextFieldOpcao2;
    private javax.swing.JTextField jTextFieldOpcao3;
    private javax.swing.JTextField jTextFieldOpcao4;
    private javax.swing.JTextField jTextFieldPergunta;
    private javax.swing.JTextField jTextFieldResposta;
    private javax.swing.JTextField jTextFieldTitulo;
    private javax.swing.JTextField jTextFieldlOpcao1;
    // End of variables declaration//GEN-END:variables
}
