/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package viewsCRUD;

import controle.AtividadeControler;
import dao.AtividadeDao;
import java.util.ArrayList;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import model.Atividade;

/**
 *
 * @author rb29
 */
public class ExcluirAtividade extends javax.swing.JInternalFrame {

    DefaultComboBoxModel modelo;

    /**
     * Creates new form ExcluirAtividade
     */
    public ExcluirAtividade() {
        initComponents();
        modelo = (DefaultComboBoxModel) jComboBoxOption.getModel();
        ExcluirAtividade();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        Senha = new javax.swing.JLabel();
        jTextFieldTitulo = new javax.swing.JTextField();
        jTextFieldPergunta = new javax.swing.JTextField();
        jTextFieldDescricao = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jTextFieldId = new javax.swing.JTextField();
        jComboBoxOption = new javax.swing.JComboBox<>();
        excluir = new javax.swing.JButton();
        nomepassed = new javax.swing.JTextField();
        search = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Excluir Atividade", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 18))); // NOI18N
        setClosable(true);
        setMaximizable(true);
        setResizable(true);
        try {
            setSelected(true);
        } catch (java.beans.PropertyVetoException e1) {
            e1.printStackTrace();
        }
        setVisible(false);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jPanel1.setBackground(new java.awt.Color(153, 204, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Excluir", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 24))); // NOI18N
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(null);

        Senha.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Senha.setText("Pergunta");
        jPanel1.add(Senha);
        Senha.setBounds(20, 240, 90, 30);

        jTextFieldTitulo.setEditable(false);
        jTextFieldTitulo.setBackground(new java.awt.Color(255, 255, 255));
        jTextFieldTitulo.setEnabled(false);
        jTextFieldTitulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldTituloActionPerformed(evt);
            }
        });
        jPanel1.add(jTextFieldTitulo);
        jTextFieldTitulo.setBounds(120, 160, 350, 30);

        jTextFieldPergunta.setEnabled(false);
        jTextFieldPergunta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldPerguntaActionPerformed(evt);
            }
        });
        jPanel1.add(jTextFieldPergunta);
        jTextFieldPergunta.setBounds(120, 240, 350, 30);

        jTextFieldDescricao.setEnabled(false);
        jTextFieldDescricao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldDescricaoActionPerformed(evt);
            }
        });
        jPanel1.add(jTextFieldDescricao);
        jTextFieldDescricao.setBounds(120, 200, 350, 30);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setText("Titulo");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(20, 160, 70, 30);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setText("ID:");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(20, 120, 30, 30);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setText("Descrição");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(20, 200, 90, 30);

        jTextFieldId.setEditable(false);
        jTextFieldId.setBackground(new java.awt.Color(255, 255, 255));
        jTextFieldId.setEnabled(false);
        jTextFieldId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldIdActionPerformed(evt);
            }
        });
        jPanel1.add(jTextFieldId);
        jTextFieldId.setBounds(120, 120, 60, 30);

        jComboBoxOption.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBoxOptionItemStateChanged(evt);
            }
        });
        jComboBoxOption.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jComboBoxOptionMouseReleased(evt);
            }
        });
        jComboBoxOption.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxOptionActionPerformed(evt);
            }
        });
        jPanel1.add(jComboBoxOption);
        jComboBoxOption.setBounds(610, 80, 130, 30);

        excluir.setBackground(new java.awt.Color(255, 255, 255));
        excluir.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        excluir.setText("Excluir");
        excluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                excluirActionPerformed(evt);
            }
        });
        jPanel1.add(excluir);
        excluir.setBounds(190, 290, 190, 40);
        jPanel1.add(nomepassed);
        nomepassed.setBounds(120, 80, 340, 30);

        search.setBackground(new java.awt.Color(255, 255, 255));
        search.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        search.setText("Procurar");
        search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchActionPerformed(evt);
            }
        });
        jPanel1.add(search);
        search.setBounds(470, 80, 120, 30);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Digite o Titulo do Atividade");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(160, 40, 250, 30);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(92, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 745, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(77, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(67, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 344, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(68, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setBounds(0, 0, 926, 513);
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBoxOptionItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBoxOptionItemStateChanged

        Atividade atividade = (Atividade) modelo.getSelectedItem();

        jTextFieldTitulo.setText(atividade.getTitulo());
        jTextFieldDescricao.setText(atividade.getDescricao());
        jTextFieldPergunta.setText(atividade.getPergunta());

        jTextFieldId.setText(atividade.getId() + "");

    }//GEN-LAST:event_jComboBoxOptionItemStateChanged

    private void jComboBoxOptionMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jComboBoxOptionMouseReleased

    }//GEN-LAST:event_jComboBoxOptionMouseReleased

    private void jComboBoxOptionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxOptionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxOptionActionPerformed

    private void searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchActionPerformed
        AtividadeControler controle = new AtividadeControler();
        Atividade atividade = controle.procuraAtividade(nomepassed.getText());
        if (atividade != null) {

            jTextFieldTitulo.setText(atividade.getTitulo());
            jTextFieldDescricao.setText(atividade.getDescricao());
            jTextFieldPergunta.setText(atividade.getPergunta());
            jTextFieldId.setText(atividade.getId() + "");
            JOptionPane.showMessageDialog(null, "Usuário Confirmado!!");
        } else {
            JOptionPane.showMessageDialog(null, "Usuário não Confirmado!!");
        }
    }//GEN-LAST:event_searchActionPerformed

    private void excluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_excluirActionPerformed
        // TODO add your handling code here:
        AtividadeControler controle = new AtividadeControler();
        int idUser = Integer.parseInt(jTextFieldId.getText());
        controle.ExcluirAtividade(idUser);

    }

    public void ExcluirAtividade() {
        AtividadeControler controle = new AtividadeControler();
        ArrayList<Atividade> vetorDeAtividades = controle.buscarAtividade();
        for (Atividade u : vetorDeAtividades) {
            modelo.addElement(u);
        }
    }//GEN-LAST:event_excluirActionPerformed

    private void jTextFieldTituloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldTituloActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldTituloActionPerformed

    private void jTextFieldPerguntaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldPerguntaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldPerguntaActionPerformed

    private void jTextFieldDescricaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldDescricaoActionPerformed

        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldDescricaoActionPerformed

    private void jTextFieldIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldIdActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Senha;
    private javax.swing.JButton excluir;
    private javax.swing.JComboBox<String> jComboBoxOption;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField jTextFieldDescricao;
    private javax.swing.JTextField jTextFieldId;
    private javax.swing.JTextField jTextFieldPergunta;
    private javax.swing.JTextField jTextFieldTitulo;
    private javax.swing.JTextField nomepassed;
    private javax.swing.JButton search;
    // End of variables declaration//GEN-END:variables
}
